[toolchain]
channel = "1.78.0"
# llvm-tools-preview is required for grcov coverage 
components = ["rustfmt", "clippy", "llvm-tools-preview", "rust-analyzer"]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]